version: "3.9"
services:
    ubuntu:
        container_name: ubuntu
        build: .
        volumes:
            - ./images:/images
            - ./scripts:/scripts
        command: tail -f /dev/null